<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RootNamespace>NSign</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="$(CoverletCollectorVersionWildcard)" />
    <PackageReference Include="coverlet.MTP" Version="$(CoverletCollectorVersionWildcard)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(SystemDependencyVersionWildcard)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(SystemDependencyVersionWildcard)" />
    <PackageReference Include="Moq" Version="$(MoqVersionWildcard)" />
    <PackageReference Include="xunit.v3" Version="$(XunitVersionWildcard)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NSign.AspNetCore\NSign.AspNetCore.csproj" />
  </ItemGroup>
</Project>
